[package]
name = "hexagon"
version = "0.1.0"
authors = ["EternalKnight17 <eternalknight17@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
